/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as IngredientsNewRouteImport } from './routes/ingredients.new'
import { Route as IngredientsIngredientIdRouteImport } from './routes/ingredients.$ingredientId'
import { Route as IngredientsIngredientIdEditRouteImport } from './routes/ingredients.$ingredientId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdRoute = IngredientsIngredientIdRouteImport.update({
  id: '/ingredients/$ingredientId',
  path: '/ingredients/$ingredientId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => IngredientsIngredientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes': typeof RecipesIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRouteWithChildren
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/'
    | '/ingredients/$ingredientId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes'
    | '/ingredients/$ingredientId/edit'
  id:
    | '__root__'
    | '/'
    | '/ingredients/$ingredientId'
    | '/ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/'
    | '/ingredients/$ingredientId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientsIngredientIdRoute: typeof IngredientsIngredientIdRouteWithChildren
  IngredientsNewRoute: typeof IngredientsNewRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId': {
      id: '/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof IngredientsIngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId/edit': {
      id: '/ingredients/$ingredientId/edit'
      path: '/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditRouteImport
      parentRoute: typeof IngredientsIngredientIdRoute
    }
  }
}

interface IngredientsIngredientIdRouteChildren {
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
}

const IngredientsIngredientIdRouteChildren: IngredientsIngredientIdRouteChildren =
  {
    IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
  }

const IngredientsIngredientIdRouteWithChildren =
  IngredientsIngredientIdRoute._addFileChildren(
    IngredientsIngredientIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientsIngredientIdRoute: IngredientsIngredientIdRouteWithChildren,
  IngredientsNewRoute: IngredientsNewRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
