/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UsernameIndexRouteImport } from './routes/$username.index'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as IngredientsNewRouteImport } from './routes/ingredients.new'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as UsernameRecipeSlugRouteImport } from './routes/$username.$recipeSlug'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes.$recipeId.index'
import { Route as IngredientsIngredientIdIndexRouteImport } from './routes/ingredients.$ingredientId.index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes.$recipeId.edit'
import { Route as IngredientsIngredientIdEditRouteImport } from './routes/ingredients.$ingredientId.edit'
import { Route as UsernameIngredientsSlugRouteImport } from './routes/$username.ingredients.$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/messages/$username',
  path: '/messages/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRecipeSlugRoute = UsernameRecipeSlugRouteImport.update({
  id: '/$username/$recipeSlug',
  path: '/$username/$recipeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdIndexRoute =
  IngredientsIngredientIdIndexRouteImport.update({
    id: '/ingredients/$ingredientId/',
    path: '/ingredients/$ingredientId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditRouteImport.update({
    id: '/ingredients/$ingredientId/edit',
    path: '/ingredients/$ingredientId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsernameIngredientsSlugRoute = UsernameIngredientsSlugRouteImport.update({
  id: '/$username/ingredients/$slug',
  path: '/$username/ingredients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$username/$recipeSlug': typeof UsernameRecipeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/recipes/new': typeof RecipesNewRoute
  '/$username/': typeof UsernameIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/$username/ingredients/$slug': typeof UsernameIngredientsSlugRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/ingredients/$ingredientId/': typeof IngredientsIngredientIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$username/$recipeSlug': typeof UsernameRecipeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/recipes/new': typeof RecipesNewRoute
  '/$username': typeof UsernameIndexRoute
  '/blog': typeof BlogIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/$username/ingredients/$slug': typeof UsernameIngredientsSlugRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdIndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset': typeof ResetRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/$username/$recipeSlug': typeof UsernameRecipeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/recipes/new': typeof RecipesNewRoute
  '/$username/': typeof UsernameIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/$username/ingredients/$slug': typeof UsernameIngredientsSlugRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/ingredients/$ingredientId/': typeof IngredientsIngredientIdIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/reset'
    | '/settings'
    | '/signup'
    | '/verify'
    | '/$username/$recipeSlug'
    | '/blog/$slug'
    | '/ingredients/new'
    | '/messages/$username'
    | '/recipes/new'
    | '/$username/'
    | '/blog/'
    | '/ingredients/'
    | '/messages/'
    | '/recipes/'
    | '/$username/ingredients/$slug'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/edit'
    | '/ingredients/$ingredientId/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/reset'
    | '/settings'
    | '/signup'
    | '/verify'
    | '/$username/$recipeSlug'
    | '/blog/$slug'
    | '/ingredients/new'
    | '/messages/$username'
    | '/recipes/new'
    | '/$username'
    | '/blog'
    | '/ingredients'
    | '/messages'
    | '/recipes'
    | '/$username/ingredients/$slug'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/edit'
    | '/ingredients/$ingredientId'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/reset'
    | '/settings'
    | '/signup'
    | '/verify'
    | '/$username/$recipeSlug'
    | '/blog/$slug'
    | '/ingredients/new'
    | '/messages/$username'
    | '/recipes/new'
    | '/$username/'
    | '/blog/'
    | '/ingredients/'
    | '/messages/'
    | '/recipes/'
    | '/$username/ingredients/$slug'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/edit'
    | '/ingredients/$ingredientId/'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetRoute: typeof ResetRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  UsernameRecipeSlugRoute: typeof UsernameRecipeSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  MessagesUsernameRoute: typeof MessagesUsernameRoute
  RecipesNewRoute: typeof RecipesNewRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  UsernameIngredientsSlugRoute: typeof UsernameIngredientsSlugRoute
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  IngredientsIngredientIdIndexRoute: typeof IngredientsIngredientIdIndexRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/messages/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$recipeSlug': {
      id: '/$username/$recipeSlug'
      path: '/$username/$recipeSlug'
      fullPath: '/$username/$recipeSlug'
      preLoaderRoute: typeof UsernameRecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId/': {
      id: '/ingredients/$ingredientId/'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId/'
      preLoaderRoute: typeof IngredientsIngredientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId/edit': {
      id: '/ingredients/$ingredientId/edit'
      path: '/ingredients/$ingredientId/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/ingredients/$slug': {
      id: '/$username/ingredients/$slug'
      path: '/$username/ingredients/$slug'
      fullPath: '/$username/ingredients/$slug'
      preLoaderRoute: typeof UsernameIngredientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ResetRoute: ResetRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  UsernameRecipeSlugRoute: UsernameRecipeSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  MessagesUsernameRoute: MessagesUsernameRoute,
  RecipesNewRoute: RecipesNewRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  UsernameIngredientsSlugRoute: UsernameIngredientsSlugRoute,
  IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  IngredientsIngredientIdIndexRoute: IngredientsIngredientIdIndexRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
