// This file has been generated by Specta. Do not edit this file manually.
//! The SDK's wire types — GENERATED from the server's wire contract (vegify-api-types, via
//! specta-rust). Do not edit; regenerate with `just bindings` (CI's build-types job fails on
//! drift). Field idents are the wire names verbatim, so the serde derives carry no renames.

/// One conversation row of the DM list, newest-message first.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct ConversationSummary {
    /// Conversation id.
    pub id: ::std::string::String,
    /// The other party.
    pub with: Party,
    /// Body of the newest message (the list's preview line).
    pub lastBody: ::std::string::String,
    /// Newest message timestamp, ms epoch.
    pub lastAt: i64,
    /// True when the last message is the viewer's own (the list renders "You: …").
    pub lastIsMine: bool,
    /// Count of messages the viewer has not read (SQLite COUNT() is i64).
    pub unread: i64,
}

/// One DM as the thread screen renders it.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct Message {
    /// Message id.
    pub id: ::std::string::String,
    /// Message body (plain text).
    pub body: ::std::string::String,
    /// Send timestamp, ms epoch.
    pub createdAt: i64,
    /// True when the viewer sent it (clients render alignment off this, not off raw ids).
    pub mine: bool,
}

/// The other party, as the conversation list + thread header shows them.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct Party {
    /// User id.
    pub id: ::std::string::String,
    /// Display name.
    pub name: ::std::string::String,
    /// Public handle (`/<username>`).
    pub username: ::std::string::String,
}

/// One ingredient row as pulled (server-authoritative mirror source).
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullIngredient {
    /// Ingredient id (stable cross-replica).
    pub id: ::std::string::String,
    /// Owner id; None = the communal catalog.
    pub userId: ::std::option::Option<::std::string::String>,
    /// Visibility as stored — the shared enum, not a loose string (same wire bytes).
    pub visibility: Visibility,
    /// Ingredient name.
    pub name: ::std::string::String,
    /// Optional description.
    pub description: ::std::option::Option<::std::string::String>,
    /// Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
    /// mirror is i32, the TS side is number — an i64 here was silent width drift in the wire contract
    /// (found by the specta-side repo audit; the class of bug a generated client would make impossible).
    /// Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
    /// mirror is i32, the TS side is number — an i64 here was silent width drift in the wire
    /// contract (found by the specta-side repo audit; the class of bug a generated client kills).
    pub price: ::std::option::Option<i32>,
    /// Calories per 100 g, when known.
    pub caloriesPer100g: ::std::option::Option<f64>,
    /// Serving size in grams, when declared.
    pub servingGrams: ::std::option::Option<f64>,
    /// The serving's unit name (a count unit like "bun"/"slice"; "serving" by default) — the recipe
    /// composer offers it as a count unit. None ⇒ no serving declared.
    pub servingUnit: ::std::option::Option<::std::string::String>,
    /// Package mass in grams, when declared.
    pub packageGrams: ::std::option::Option<f64>,
    /// Current slug; mirrored verbatim so local links match the server.
    pub slug: ::std::option::Option<::std::string::String>,
    /// Soft-delete tombstone (ms epoch). Tombstoned rows STAY in the pull — recipes that use them
    /// need the data — and clients mirror the flag so their local list/search filtering matches.
    pub deletedAt: ::std::option::Option<i64>,
    /// Per-100 g nutrient rows.
    pub nutrients: ::std::vec::Vec<PullReading>,
}

/// One recipe line as pulled.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullItem {
    /// The ingredient the line references.
    pub ingredientId: ::std::string::String,
    /// Line quantity in grams (canonical).
    pub grams: f64,
    /// Display unit the author picked; None = grams.
    pub unit: ::std::option::Option<::std::string::String>,
    /// The count in `unit` (e.g. 2 for "2 buns") — carried so a replica shows the author's units, not
    /// raw grams. None on a legacy row (the applier falls back to grams).
    pub amount: ::std::option::Option<f64>,
}

/// One full sync pull: every server row visible to the device's user.
/// Server-authoritative — the desktop mirrors these verbatim.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullPayload {
    /// All visible recipes, with their lines.
    pub recipes: ::std::vec::Vec<PullRecipe>,
    /// All visible ingredients, with their nutrient rows.
    pub ingredients: ::std::vec::Vec<PullIngredient>,
    /// The creators of the rows above — public identity only. The desktop mirrors these into its
    /// local `users` cache so creator handles and `/<username>` profiles resolve on-device, logged
    /// out included. Users without a username are omitted (their content renders creatorless,
    /// exactly as the server serves it).
    pub users: ::std::vec::Vec<PullUser>,
}

/// One nutrient reading as pulled, per 100 g.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullReading {
    /// Nutrient name.
    pub name: ::std::string::String,
    /// Quantity per 100 g.
    pub amountPer100g: f64,
    /// Unit for the quantity (g, mg, µg).
    pub unit: ::std::string::String,
}

/// One recipe row as pulled (server-authoritative mirror source).
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullRecipe {
    /// Recipe id (stable cross-replica).
    pub id: ::std::string::String,
    /// The recipe's as-ingredient pair id — must survive the mirror so
    /// consuming items' FKs stay intact.
    pub asIngredientId: ::std::string::String,
    /// Owner id; None = ownerless seed content.
    pub userId: ::std::option::Option<::std::string::String>,
    /// Visibility as stored — the shared enum, not a loose string (same wire bytes; the
    /// TS side tightens to the "public" | "private" | "unlisted" union).
    pub visibility: Visibility,
    /// Recipe title.
    pub name: ::std::string::String,
    /// Optional subtitle.
    pub subtitle: ::std::option::Option<::std::string::String>,
    /// Free-text directions.
    pub directions: ::std::option::Option<::std::string::String>,
    /// Serving size in grams, when declared.
    pub servingGrams: ::std::option::Option<f64>,
    /// Total batch mass in grams, when declared.
    pub batchGrams: ::std::option::Option<f64>,
    /// Current slug; mirrored verbatim so local links match the server.
    pub slug: ::std::option::Option<::std::string::String>,
    /// The recipe's lines, in order.
    pub items: ::std::vec::Vec<PullItem>,
}

/// One creator as pulled — the public identity surface for content in this payload.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PullUser {
    /// User id (what PullRecipe/PullIngredient `user_id` points at).
    pub id: ::std::string::String,
    /// Profile handle (the `/<username>` URL segment).
    pub username: ::std::string::String,
    /// Display name.
    pub name: ::std::string::String,
    /// Media key of the profile avatar; clients compose `<api base>/<key>`.
    pub avatarKey: ::std::option::Option<::std::string::String>,
}

/// A thread as the thread screen consumes it: the other party (resolved even before any message
/// exists, so a profile's "Message" button lands on an empty composer) + the messages, oldest first.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct Thread {
    /// The other party (resolved even for an empty thread).
    pub with: Party,
    /// The messages, oldest first.
    pub messages: ::std::vec::Vec<Message>,
}

/// The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
/// direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
/// ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
/// EDITING, not reading.
#[allow(deprecated, non_camel_case_types, non_snake_case)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub enum Visibility {
    /// Listed and readable by everyone.
    public,
    /// Readable only by the owner.
    private,
    /// Readable via direct link; never listed or searched.
    unlisted,
}

