// @vegify/api-types — GENERATED from vegify-core's wire shapes (the server's serde source of
// truth). Do not edit; regenerate with `just bindings` (CI's build-types job fails on drift).

// This file has been generated by Specta. Do not edit this file manually.
export type AggregatedNutrition = {
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Amount = {
	amount: number | null,
	unit: string | null,
	grams: number | null,
};

/**  Ingredient browser card (leaf ingredients — those not backing a recipe). */
export type IngredientCard = {
	id: string,
	name: string,
	caloriesPer100g: number | null,
	/**  Slug for the canonical `/ingredients/<slug>` link; fall back to `/ingredients/<id>`. */
	slug: string | null,
};

/**  IngredientForm edit-mode source data (per-100g; the frontend scales to per-serving). */
export type IngredientEditData = {
	id: string,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	nutrients: Reading[],
};

export type IngredientSearchResult = {
	id: string,
	name: string,
	servingGrams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

/**
 *  A public profile: the handle, the display name, and the user's visible recipes. Shared by the
 *  server's `/api/content/profile` endpoint and the desktop DAL so both render the identical screen.
 */
export type Profile = {
	username: string,
	name: string,
	recipes: RecipeCard[],
};

export type Reading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type RecipeCard = {
	id: string,
	name: string,
	subtitle: string | null,
	/**
	 *  Owner handle + slug for the canonical `/<username>/<slug>` link. Optional (pre-backfill /
	 *  ownerless rows); the UI falls back to `/recipes/<id>` when either is missing.
	 */
	username: string | null,
	slug: string | null,
};

export type RecipeEditData = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servings: number | null,
	visibility: Visibility,
	items: RecipeEditItem[],
};

/**  RecipeForm edit-mode defaults: per-item nutrition included so each row shows live nutrition. */
export type RecipeEditItem = {
	ingredientId: string,
	name: string,
	grams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type RecipeItem = {
	id: string,
	name: string,
	amount: Amount,
	/**
	 *  Set when this item is itself a recipe-as-ingredient (e.g. a Biga in a Dough),
	 *  so the UI links to that recipe's page instead of a (sparse) ingredient page.
	 */
	recipeId: string | null,
	/**
	 *  True only in the DELETER's own recipes: the ingredient is soft-deleted (tombstoned) AND its
	 *  owner owns this recipe. Other users' recipes render the same ingredient normally — a soft
	 *  delete disowns from the catalog without breaking anyone's recipe. Drives the greyed row +
	 *  the "restore?" affordance.
	 */
	deleted: boolean,
};

export type RecipeView = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
};

/**
 *  The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
 *  direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
 *  ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
 *  EDITING, not reading.
 */
export type Visibility = "public" | "private" | "unlisted";
