// @vegify/api-types — GENERATED from the server's wire shapes (vegify-core + services/api handler
// responses; the api TypeCollection in services/api/types). Do not edit; regenerate with
// `just bindings` (CI's build-types job fails on drift).

// This file has been generated by Specta. Do not edit this file manually.
export type AggregatedNutrition = {
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Amount = {
	amount: number | null,
	unit: string | null,
	grams: number | null,
};

export type ConversationSummary = {
	id: string,
	with: Party,
	lastBody: string,
	lastAt: number | null,
	/**  True when the last message is the viewer's own (the list renders "You: …"). */
	lastIsMine: boolean,
	unread: number | null,
};

/**  Ingredient browser card (leaf ingredients — those not backing a recipe). */
export type IngredientCard = {
	id: string,
	name: string,
	caloriesPer100g: number | null,
	/**  Slug for the canonical `/ingredients/<slug>` link; fall back to `/ingredients/<id>`. */
	slug: string | null,
};

/**  IngredientForm edit-mode source data (per-100g; the frontend scales to per-serving). */
export type IngredientEditData = {
	id: string,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	nutrients: Reading[],
};

export type IngredientSearchResult = {
	id: string,
	name: string,
	servingGrams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type IngredientSlugHit = {
	ingredientId: string,
	canonicalSlug: string,
};

/**
 *  Wire-facing JSON for opaque per-kind payloads (mirrors the UI's JsonValue). Exists because the
 *  rc.25 specta line can't export `serde_json::Value` — its Number variant carries i64 and trips
 *  the BigInt guard (fixed upstream by specta PR #505; when that lands, the `#[specta(type = …)]`
 *  overrides pointing here can drop away). Never constructed — a type-level wire declaration only.
 */
export type JsonValue = null | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type Message = {
	id: string,
	body: string,
	createdAt: number | null,
	/**  True when the viewer sent it (clients render alignment off this, not off raw ids). */
	mine: boolean,
};

export type Notification = {
	id: string,
	kind: string,
	/**
	 *  Parsed payload — per-kind (kind "ingredient-updated": `{ingredient: {id,name,slug}, by: {name,username}}`).
	 *  Wire-declared as the crate's JsonValue: specta rc.25 can't export serde_json::Value (see lib.rs).
	 */
	payload: JsonValue,
	createdAt: number | null,
	read: boolean,
};

/**  The other party, as the conversation list + thread header shows them. */
export type Party = {
	id: string,
	name: string,
	username: string,
};

/**  Full post — `body` is the parsed JSON block list the web renders. */
export type PostFull = {
	slug: string,
	title: string,
	description: string,
	datePublished: string,
	dateDisplay: string,
	/**  Wire-declared as the crate's JsonValue: specta rc.25 can't export serde_json::Value (see lib.rs). */
	body: JsonValue,
};

/**  Index-card shape (no body). */
export type PostSummary = {
	slug: string,
	title: string,
	description: string,
	datePublished: string,
	dateDisplay: string,
};

/**
 *  A public profile: the handle, the display name, and the user's visible recipes. Shared by the
 *  server's `/api/content/profile` endpoint and the desktop DAL so both render the identical screen.
 */
export type Profile = {
	username: string,
	name: string,
	recipes: RecipeCard[],
};

export type PullIngredient = {
	id: string,
	userId: string | null,
	visibility: string,
	name: string,
	description: string | null,
	/**
	 *  Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
	 *  mirror is i32, the TS side is number — an i64 here was silent width drift in the wire contract
	 *  (found by the specta-side repo audit; the class of bug a generated client would make impossible).
	 *  Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
	 *  mirror is i32, the TS side is number — an i64 here was silent width drift in the wire
	 *  contract (found by the specta-side repo audit; the class of bug a generated client kills).
	 */
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	slug: string | null,
	/**
	 *  Soft-delete tombstone (ms). Tombstoned rows STAY in the pull — recipes that use them need
	 *  the data — and clients mirror the flag so their local list/search filtering matches.
	 */
	deletedAt: number | null,
	nutrients: PullReading[],
};

export type PullItem = {
	ingredientId: string,
	grams: number | null,
	unit: string | null,
};

export type PullPayload = {
	recipes: PullRecipe[],
	ingredients: PullIngredient[],
};

export type PullReading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type PullRecipe = {
	id: string,
	asIngredientId: string,
	userId: string | null,
	visibility: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servingGrams: number | null,
	batchGrams: number | null,
	slug: string | null,
	items: PullItem[],
};

export type Reading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type RecipeCard = {
	id: string,
	name: string,
	subtitle: string | null,
	/**
	 *  Owner handle + slug for the canonical `/<username>/<slug>` link. Optional (pre-backfill /
	 *  ownerless rows); the UI falls back to `/recipes/<id>` when either is missing.
	 */
	username: string | null,
	slug: string | null,
};

export type RecipeEditData = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servings: number | null,
	visibility: Visibility,
	items: RecipeEditItem[],
};

/**  RecipeForm edit-mode defaults: per-item nutrition included so each row shows live nutrition. */
export type RecipeEditItem = {
	ingredientId: string,
	name: string,
	grams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type RecipeItem = {
	id: string,
	name: string,
	amount: Amount,
	/**
	 *  Set when this item is itself a recipe-as-ingredient (e.g. a Biga in a Dough),
	 *  so the UI links to that recipe's page instead of a (sparse) ingredient page.
	 */
	recipeId: string | null,
	/**
	 *  True only in the DELETER's own recipes: the ingredient is soft-deleted (tombstoned) AND its
	 *  owner owns this recipe. Other users' recipes render the same ingredient normally — a soft
	 *  delete disowns from the catalog without breaking anyone's recipe. Drives the greyed row +
	 *  the "restore?" affordance.
	 */
	deleted: boolean,
};

export type RecipeSlugHit = {
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
};

export type RecipeView = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
};

/**
 *  The public, canonical, indexable URLs — everything with a slug that anyone can read. Recipes carry
 *  their owner handle (for `/<username>/<slug>`); ingredients are the global catalog (`/ingredients/<slug>`).
 */
export type SitemapData = {
	recipes: SitemapRecipe[],
	ingredients: string[],
};

export type SitemapRecipe = {
	username: string,
	slug: string,
};

/**
 *  A thread as the thread screen consumes it: the other party (resolved even before any message
 *  exists, so a profile's "Message" button lands on an empty composer) + the messages, oldest first.
 */
export type Thread = {
	with: Party,
	messages: Message[],
};

/**
 *  The signed-in user — the `{id, name, username, email}` the auth routes return, and the viewer the content
 *  gates scope to. Serializes with bare field names (matching the web's response).
 */
export type User = {
	id: string,
	name: string,
	/**  Public handle backing `/<username>`. Assigned at signup (see [`derive_unique_username`]). */
	username: string,
	email: string,
	/**
	 *  Whether `users.email_verified_at` is set — surfaced to the clients so they can prompt for
	 *  verification (and gate verified-only actions later) without a second round trip.
	 */
	email_verified: boolean,
};

/**
 *  The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
 *  direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
 *  ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
 *  EDITING, not reading.
 */
export type Visibility = "public" | "private" | "unlisted";
