// @vegify/api-types — GENERATED from the server's wire shapes (vegify-core + services/api handler
// responses; the api TypeCollection in services/api/types). Do not edit; regenerate with
// `just bindings` (CI's build-types job fails on drift).

// This file has been generated by Specta. Do not edit this file manually.
/**  A recipe's nutrition rolled up from its items, per 100 g. */
export type AggregatedNutrition = {
	/**  Calories per 100 g; None when no item carries calorie data. */
	caloriesPer100g: number | null,
	/**  Per-100 g readings summed across items, keyed by nutrient name. */
	readings: Reading[],
};

/**
 *  A quantity as entered plus its canonical mass: `grams` is the ground
 *  truth all math runs on; `amount`/`unit` preserve how the user wrote it.
 */
export type Amount = {
	/**  Quantity in `unit`, as entered; None when only the mass is known. */
	amount: number | null,
	/**  Display unit (cup, tbsp, g); None when only the mass is known. */
	unit: string | null,
	/**  Canonical mass in grams. */
	grams: number | null,
};

/**  One conversation row of the DM list, newest-message first. */
export type ConversationSummary = {
	/**  Conversation id. */
	id: string,
	/**  The other party. */
	with: Party,
	/**  Body of the newest message (the list's preview line). */
	lastBody: string,
	/**  Newest message timestamp, ms epoch. */
	lastAt: number | null,
	/**  True when the last message is the viewer's own (the list renders "You: …"). */
	lastIsMine: boolean,
	/**  Count of messages the viewer has not read. */
	unread: number | null,
};

/**  Ingredient browser card (leaf ingredients — those not backing a recipe). */
export type IngredientCard = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Calories per 100 g, when known (list-card badge). */
	caloriesPer100g: number | null,
	/**  Slug for the canonical link; fall back to `/ingredients/<id>`. */
	slug: string | null,
	/**
	 *  Owner handle: an OWNED ingredient is canonical at `/<username>/ingredients/<slug>` (browsable
	 *  under its creator); None = the communal catalog, canonical at `/ingredients/<slug>`.
	 */
	username: string | null,
};

/**  IngredientForm edit-mode source data (per-100g; the frontend scales to per-serving). */
export type IngredientEditData = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Optional description shown on the detail page. */
	description: string | null,
	/**  Price in cents, when tracked. */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**  Package mass in grams, when declared (price-per-100 g math). */
	packageGrams: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	/**  Owner handle (None = the communal catalog) — the detail page's breadcrumb + canonical URL. */
	creator: string | null,
	/**  Per-100 g nutrient rows as stored (the form scales to per-serving). */
	nutrients: Reading[],
};

/**  One ingredient hit in the recipe composer's search box. */
export type IngredientSearchResult = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**
	 *  Serving size in grams, when the ingredient declares one (the composer's
	 *  default line quantity).
	 */
	servingGrams: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Per-100 g nutrient readings, for the composer's live nutrition preview. */
	readings: Reading[],
};

/**  Resolution of an ingredient slug (current or historical) to its row. */
export type IngredientSlugHit = {
	/**  The ingredient the slug resolves to. */
	ingredientId: string,
	/**
	 *  The ingredient's CURRENT slug — differs when the hit came from slug
	 *  history, in which case the caller 301s here.
	 */
	canonicalSlug: string,
	/**
	 *  Owner handle when the ingredient is user-owned: `/ingredients/<slug>` 301s to
	 *  `/<username>/ingredients/<slug>` (the catalog stays at the global path).
	 */
	username: string | null,
};

/**
 *  Wire-facing JSON for opaque per-kind payloads (mirrors the UI's JsonValue). Exists because the
 *  rc.25 specta line can't export `serde_json::Value` — its Number variant carries i64 and trips
 *  the BigInt guard (fixed upstream by specta PR #505; when that lands, the `#[specta(type = …)]`
 *  overrides pointing here can drop away). Never constructed — a type-level wire declaration only.
 */
export type JsonValue = 
/**  JSON null. */
null | 
/**  JSON boolean. */
boolean | 
/**  JSON number (f64 on this wire; the reason this type exists). */
number | null | 
/**  JSON string. */
string | 
/**  JSON array. */
JsonValue[] | 
/**  JSON object. */
{ [key in string]: JsonValue };

/**  One DM as the thread screen renders it. */
export type Message = {
	/**  Message id. */
	id: string,
	/**  Message body (plain text). */
	body: string,
	/**  Send timestamp, ms epoch. */
	createdAt: number | null,
	/**  True when the viewer sent it (clients render alignment off this, not off raw ids). */
	mine: boolean,
};

/**  One bell notification. */
export type Notification = {
	/**  Notification id. */
	id: string,
	/**
	 *  Notification kind tag (e.g. "ingredient-updated"); selects the
	 *  payload shape and the client-side renderer.
	 */
	kind: string,
	/**
	 *  Parsed payload — per-kind (kind "ingredient-updated": `{ingredient: {id,name,slug}, by: {name,username}}`).
	 *  Wire-declared as the crate's JsonValue: specta rc.25 can't export serde_json::Value (see lib.rs).
	 */
	payload: JsonValue,
	/**  Creation timestamp, ms epoch. */
	createdAt: number | null,
	/**  Whether the viewer has opened it. */
	read: boolean,
};

/**  The other party, as the conversation list + thread header shows them. */
export type Party = {
	/**  User id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Public handle (`/<username>`). */
	username: string,
};

/**  Full post — `body` is the parsed JSON block list the web renders. */
export type PostFull = {
	/**  URL slug (`/blog/<slug>`). */
	slug: string,
	/**  Post title. */
	title: string,
	/**  One-to-two sentence summary (meta description + JSON-LD). */
	description: string,
	/**  RFC 3339 publication timestamp. */
	datePublished: string,
	/**  Human-formatted publication date, preformatted server-side. */
	dateDisplay: string,
	/**  Wire-declared as the crate's JsonValue: specta rc.25 can't export serde_json::Value (see lib.rs). */
	body: JsonValue,
};

/**  Index-card shape (no body). */
export type PostSummary = {
	/**  URL slug (`/blog/<slug>`). */
	slug: string,
	/**  Post title. */
	title: string,
	/**  One-to-two sentence summary (index cards + meta description). */
	description: string,
	/**  RFC 3339 publication timestamp (feeds `<time datetime>` + JSON-LD). */
	datePublished: string,
	/**  Human-formatted publication date, preformatted server-side. */
	dateDisplay: string,
};

/**
 *  A public profile: the handle, the display name, and the user's visible recipes. Shared by the
 *  server's `/api/content/profile` endpoint and the desktop DAL so both render the identical screen.
 */
export type Profile = {
	/**  The profile's handle (URL segment). */
	username: string,
	/**  Display name. */
	name: string,
	/**  The user's recipes visible to the viewer, as cards. */
	recipes: RecipeCard[],
	/**
	 *  The user's LEAF ingredients (created or imported by them), visible to the viewer and not
	 *  tombstoned — browsable under `/<username>/ingredients/<slug>`.
	 */
	ingredients: IngredientCard[],
	/**  Media key of the profile avatar; clients compose `<api base>/<key>`. */
	avatarKey: string | null,
};

/**  One ingredient row as pulled (server-authoritative mirror source). */
export type PullIngredient = {
	/**  Ingredient id (stable cross-replica). */
	id: string,
	/**  Owner id; None = the communal catalog. */
	userId: string | null,
	/**  Visibility as stored — the shared enum, not a loose string (same wire bytes). */
	visibility: Visibility,
	/**  Ingredient name. */
	name: string,
	/**  Optional description. */
	description: string | null,
	/**
	 *  Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
	 *  mirror is i32, the TS side is number — an i64 here was silent width drift in the wire contract
	 *  (found by the specta-side repo audit; the class of bug a generated client would make impossible).
	 *  Cents (USD). i32 END-TO-END: SaveIngredientInput (the only write path) is i32, the desktop
	 *  mirror is i32, the TS side is number — an i64 here was silent width drift in the wire
	 *  contract (found by the specta-side repo audit; the class of bug a generated client kills).
	 */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**  Package mass in grams, when declared. */
	packageGrams: number | null,
	/**  Current slug; mirrored verbatim so local links match the server. */
	slug: string | null,
	/**
	 *  Soft-delete tombstone (ms). Tombstoned rows STAY in the pull — recipes that use them need
	 *  the data — and clients mirror the flag so their local list/search filtering matches.
	 */
	deletedAt: number | null,
	/**  Per-100 g nutrient rows. */
	nutrients: PullReading[],
};

/**  One recipe line as pulled. */
export type PullItem = {
	/**  The ingredient the line references. */
	ingredientId: string,
	/**  Line quantity in grams (canonical). */
	grams: number | null,
	/**  Display unit the author picked; None = grams. */
	unit: string | null,
};

/**
 *  One full sync pull: every server row visible to the device's user.
 *  Server-authoritative — the desktop mirrors these verbatim.
 */
export type PullPayload = {
	/**  All visible recipes, with their lines. */
	recipes: PullRecipe[],
	/**  All visible ingredients, with their nutrient rows. */
	ingredients: PullIngredient[],
	/**
	 *  The creators of the rows above — public identity only. The desktop mirrors these into its
	 *  local `users` cache so creator handles and `/<username>` profiles resolve on-device, logged
	 *  out included. Users without a username are omitted (their content renders creatorless,
	 *  exactly as the server serves it).
	 */
	users: PullUser[],
};

/**  One nutrient reading as pulled, per 100 g. */
export type PullReading = {
	/**  Nutrient name. */
	name: string,
	/**  Quantity per 100 g. */
	amountPer100g: number | null,
	/**  Unit for the quantity (g, mg, µg). */
	unit: string,
};

/**  One recipe row as pulled (server-authoritative mirror source). */
export type PullRecipe = {
	/**  Recipe id (stable cross-replica). */
	id: string,
	/**
	 *  The recipe's as-ingredient pair id — must survive the mirror so
	 *  consuming items' FKs stay intact.
	 */
	asIngredientId: string,
	/**  Owner id; None = ownerless seed content. */
	userId: string | null,
	/**
	 *  Visibility as stored — the shared enum, not a loose string (same wire bytes; the
	 *  TS side tightens to the "public" | "private" | "unlisted" union).
	 */
	visibility: Visibility,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle. */
	subtitle: string | null,
	/**  Free-text directions. */
	directions: string | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**  Total batch mass in grams, when declared. */
	batchGrams: number | null,
	/**  Current slug; mirrored verbatim so local links match the server. */
	slug: string | null,
	/**  The recipe's lines, in order. */
	items: PullItem[],
};

/**  One creator as pulled — the public identity surface for content in this payload. */
export type PullUser = {
	/**  User id (what PullRecipe/PullIngredient `user_id` points at). */
	id: string,
	/**  Profile handle (the `/<username>` URL segment). */
	username: string,
	/**  Display name. */
	name: string,
	/**  Media key of the profile avatar; clients compose `<api base>/<key>`. */
	avatarKey: string | null,
};

/**  One nutrient measurement, normalized per 100 g. */
export type Reading = {
	/**  Nutrient name (e.g. "Iron"). */
	name: string,
	/**  Quantity per 100 g of the food. */
	amountPer100g: number | null,
	/**  Display unit for the quantity (g, mg, µg). */
	unit: string,
};

/**  Recipe list/browse card — the light projection for grids. */
export type RecipeCard = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle, shown under the title on cards. */
	subtitle: string | null,
	/**
	 *  Owner handle + slug for the canonical `/<username>/<slug>` link. Optional (pre-backfill /
	 *  ownerless rows); the UI falls back to `/recipes/<id>` when either is missing.
	 */
	username: string | null,
	/**  The recipe's slug half of the canonical link (see `username`). */
	slug: string | null,
	/**
	 *  Media key of the hero photo (attached to the recipe's as-ingredient); clients compose the
	 *  URL as `<api base>/<key>`. None = no photo yet (cards render the placeholder tile).
	 */
	photoKey: string | null,
};

/**  RecipeForm edit-mode source data (per-100 g; the frontend scales). */
export type RecipeEditData = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle. */
	subtitle: string | null,
	/**  Free-text directions; None = none written. */
	directions: string | null,
	/**  Declared servings per batch, when set. */
	servings: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  The recipe's lines in edit form. */
	items: RecipeEditItem[],
};

/**  RecipeForm edit-mode defaults: per-item nutrition included so each row shows live nutrition. */
export type RecipeEditItem = {
	/**  The referenced ingredient's id. */
	ingredientId: string,
	/**  Ingredient display name. */
	name: string,
	/**  Line quantity in grams (canonical). */
	grams: number | null,
	/**  Calories per 100 g, when known — the edit screen's live math. */
	caloriesPer100g: number | null,
	/**  Per-100 g readings for the edit screen's live nutrition roll-up. */
	readings: Reading[],
};

/**  One recipe line as read: the ingredient, its display name, its amount. */
export type RecipeItem = {
	/**  The underlying ingredient's id. */
	id: string,
	/**  Ingredient display name at read time. */
	name: string,
	/**  The line's quantity (display form + canonical grams). */
	amount: Amount,
	/**
	 *  Set when this item is itself a recipe-as-ingredient (e.g. a Biga in a Dough),
	 *  so the UI links to that recipe's page instead of a (sparse) ingredient page.
	 */
	recipeId: string | null,
	/**
	 *  True only in the DELETER's own recipes: the ingredient is soft-deleted (tombstoned) AND its
	 *  owner owns this recipe. Other users' recipes render the same ingredient normally — a soft
	 *  delete disowns from the catalog without breaking anyone's recipe. Drives the greyed row +
	 *  the "restore?" affordance.
	 */
	deleted: boolean,
};

/**  Resolution of a recipe slug (current or historical) to its row. */
export type RecipeSlugHit = {
	/**  The recipe the slug resolves to. */
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
};

/**  Full recipe detail as rendered by the recipe page. */
export type RecipeView = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle under the title. */
	subtitle: string | null,
	/**  Free-text directions (markdown-ish plain text); None = none written. */
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	/**  Serving size, when declared (drives per-serving nutrition). */
	serving: Amount | null,
	/**
	 *  Total batch mass in grams, when declared — the denominator that
	 *  turns summed item nutrition into per-100 g.
	 */
	batchGrams: number | null,
	/**  The recipe's lines, in order. */
	items: RecipeItem[],
	/**  Nutrition rolled up from the items, per 100 g. */
	nutrition: AggregatedNutrition,
	/**  Media key of the hero photo — see [`RecipeCard::photo_key`]. */
	photoKey: string | null,
};

/**
 *  A DM send, as the client must state it. The server's own deserializer stays lenient (missing
 *  fields answer 400 with a message rather than a deserialization error); the CONTRACT is that
 *  both fields are required.
 */
export type SendMessageBody = {
	/**  Recipient handle (a username). */
	to: string,
	/**  Message body (plain text). */
	body: string,
};

/**
 *  The public, canonical, indexable URLs — everything with a slug that anyone can read. Recipes and
 *  OWNED ingredients carry their owner handle; unowned ingredients are the catalog namespace.
 */
export type SitemapData = {
	/**  All indexable recipe URLs. */
	recipes: SitemapRecipe[],
	/**  All indexable ingredient URLs. */
	ingredients: SitemapIngredient[],
};

/**  One indexable ingredient URL for the sitemap. */
export type SitemapIngredient = {
	/**
	 *  Owner handle: owned rows are canonical at `/<username>/ingredients/<slug>`; None = catalog
	 *  (`/ingredients/<slug>`).
	 */
	username: string | null,
	/**  The ingredient's slug. */
	slug: string,
};

/**  Owner handle (first segment of the canonical URL). */
export type SitemapRecipe = {
	/**  Owner handle (first segment of the canonical URL). */
	username: string,
	/**  The recipe's slug (second URL segment). */
	slug: string,
};

/**
 *  Recipe browser cards. isListed: public catalog + your own (any visibility). `user_id = NULL` never
 *  matches, so a signed-out viewer (viewer = None) sees only public.
 *  Public recipe catalog for `viewer` (public rows + the viewer's own), NEWEST FIRST by id — ids are
 *  ULIDs, so id order is creation order. Keyset-paginated for infinite scroll: pass the last card's `id`
 *  as `cursor` to get the page after it; `limit` caps the page (None = no limit, i.e. the full list).
 *  Sort order for the catalog list reads. Recency sorts key on the id (ids are ULIDs, so id order is
 *  creation order); name sorts use a composite (name, id) keyset since names are not unique. Default
 *  = Newest (the catalog's first impression).
 */
export type Sort = 
/**  Newest first (creation order). */
"newest" | 
/**  Oldest first. */
"oldest" | 
/**  Name A→Z. */
"name_asc" | 
/**  Name Z→A. */
"name_desc";

/**
 *  A thread as the thread screen consumes it: the other party (resolved even before any message
 *  exists, so a profile's "Message" button lands on an empty composer) + the messages, oldest first.
 */
export type Thread = {
	/**  The other party (resolved even for an empty thread). */
	with: Party,
	/**  The messages, oldest first. */
	messages: Message[],
};

/**  An approved upload: PUT the bytes to `url` (presigned, short-lived), then attach `key`. */
export type UploadTicket = {
	/**  Storage key to attach to the row once the PUT succeeds. */
	key: string,
	/**  Presigned, short-lived PUT URL for the bytes. */
	url: string,
};

/**
 *  The signed-in user — the `{id, name, username, email}` the auth routes return, and the viewer the content
 *  gates scope to. Serializes with bare field names (matching the web's response).
 */
export type User = {
	/**  User id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Public handle backing `/<username>`. Assigned at signup (see [`derive_unique_username`]). */
	username: string,
	/**  Login/notification address; visible only to the account itself. */
	email: string,
	/**
	 *  Whether `users.email_verified_at` is set — surfaced to the clients so they can prompt for
	 *  verification (and gate verified-only actions later) without a second round trip.
	 */
	email_verified: boolean,
};

/**
 *  The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
 *  direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
 *  ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
 *  EDITING, not reading.
 */
export type Visibility = 
/**  Listed and readable by everyone. */
"public" | 
/**  Readable only by the owner. */
"private" | 
/**  Readable via direct link; never listed or searched. */
"unlisted";
