// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";

export const vegifyData = {
  /** @throws {DataError} */
  listRecipes(): Promise<RecipeCard[]> {
    return invoke("list_recipes");
  },

  /** @throws {DataError} */
  recipe(id: number): Promise<{
	id: number,
	name: string,
	subtitle: string | null,
	directions: string | null,
	creator: string | null,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
} | null> {
    return invoke("recipe", { id });
  },

  /** @throws {DataError} */
  renameRecipe(id: number, name: string): Promise<null> {
    return invoke("rename_recipe", { id, name });
  },

  /** @throws {DataError} */
  sync(): Promise<null> {
    return invoke("sync");
  },
};

export type DataError = { type: "db"; message: string };

export type AggregatedNutrition = {
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Amount = {
	amount: number | null,
	unit: string | null,
	grams: number | null,
};

export type Reading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type RecipeCard = {
	id: number,
	name: string,
	subtitle: string | null,
};

export type RecipeItem = {
	id: number,
	name: string,
	amount: Amount,
};

export type RecipeView = {
	id: number,
	name: string,
	subtitle: string | null,
	directions: string | null,
	creator: string | null,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
};
