// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";

export const vegifyData = {
  /** @throws {DataError} */
  listRecipes(): Promise<RecipeCard[]> {
    return invoke("list_recipes");
  },

  /** @throws {DataError} */
  recipe(id: string): Promise<{
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	creator: string | null,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
} | null> {
    return invoke("recipe", { id });
  },

  /** @throws {DataError} */
  searchIngredients(query: string): Promise<IngredientSearchResult[]> {
    return invoke("search_ingredients", { query });
  },

  /** @throws {DataError} */
  saveIngredient(input: SaveIngredientInput): Promise<string> {
    return invoke("save_ingredient", { input });
  },

  /** @throws {DataError} */
  deleteIngredient(id: string): Promise<null> {
    return invoke("delete_ingredient", { id });
  },

  /** @throws {DataError} */
  saveRecipe(input: SaveRecipeInput): Promise<string> {
    return invoke("save_recipe", { input });
  },

  /** @throws {DataError} */
  deleteRecipe(id: string): Promise<null> {
    return invoke("delete_recipe", { id });
  },

  /** @throws {DataError} */
  sync(): Promise<null> {
    return invoke("sync");
  },

  /** @throws {DataError} */
  compact(): Promise<null> {
    return invoke("compact");
  },
};

export type DataError = { type: "db"; message: string };

export type AggregatedNutrition = {
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Amount = {
	amount: number | null,
	unit: string | null,
	grams: number | null,
};

export type IngredientNutrientInput = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type IngredientSearchResult = {
	id: string,
	name: string,
	servingGrams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Reading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type RecipeCard = {
	id: string,
	name: string,
	subtitle: string | null,
};

export type RecipeItem = {
	id: string,
	name: string,
	amount: Amount,
};

export type RecipeItemInput = {
	ingredientId: string,
	grams: number | null,
	unit: string | null,
};

export type RecipeView = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	creator: string | null,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
};

export type SaveIngredientInput = {
	id: string | null,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	nutrients: IngredientNutrientInput[],
};

export type SaveRecipeInput = {
	id: string | null,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servingGrams: number | null,
	batchGrams: number | null,
	items: RecipeItemInput[],
};
