// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";

export const vegifyData = {
  /** @throws {DataError} */
  listRecipes(page: Page): Promise<RecipeCard[]> {
    return invoke("list_recipes", { page });
  },

  /** @throws {DataError} */
  recipe(id: string): Promise<{
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
} | null> {
    return invoke("recipe", { id });
  },

  /** @throws {DataError} */
  getProfile(username: string): Promise<{
	username: string,
	name: string,
	recipes: RecipeCard[],
} | null> {
    return invoke("get_profile", { username });
  },

  /** @throws {DataError} */
  resolveRecipeBySlug(username: string, slug: string): Promise<{
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
} | null> {
    return invoke("resolve_recipe_by_slug", { username, slug });
  },

  /** @throws {DataError} */
  resolveIngredientBySlug(slug: string): Promise<{
	ingredientId: string,
	canonicalSlug: string,
} | null> {
    return invoke("resolve_ingredient_by_slug", { slug });
  },

  /** @throws {DataError} */
  recipeForEdit(id: string): Promise<{
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servings: number | null,
	visibility: Visibility,
	items: RecipeEditItem[],
} | null> {
    return invoke("recipe_for_edit", { id });
  },

  /** @throws {DataError} */
  listIngredients(page: Page): Promise<IngredientCard[]> {
    return invoke("list_ingredients", { page });
  },

  /** @throws {DataError} */
  ingredient(id: string): Promise<{
	id: string,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	nutrients: Reading[],
} | null> {
    return invoke("ingredient", { id });
  },

  /** @throws {DataError} */
  ingredientForEdit(id: string): Promise<{
	id: string,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	nutrients: Reading[],
} | null> {
    return invoke("ingredient_for_edit", { id });
  },

  /** @throws {DataError} */
  searchIngredients(query: string): Promise<IngredientSearchResult[]> {
    return invoke("search_ingredients", { query });
  },

  /** @throws {DataError} */
  saveIngredient(input: SaveIngredientInput): Promise<string> {
    return invoke("save_ingredient", { input });
  },

  /** @throws {DataError} */
  deleteIngredient(id: string): Promise<null> {
    return invoke("delete_ingredient", { id });
  },

  /** @throws {DataError} */
  saveRecipe(input: SaveRecipeInput): Promise<string> {
    return invoke("save_recipe", { input });
  },

  /** @throws {DataError} */
  deleteRecipe(id: string): Promise<null> {
    return invoke("delete_recipe", { id });
  },

  /** @throws {DataError} */
  syncNow(): Promise<null> {
    return invoke("sync_now");
  },

  /** @throws {DataError} */
  currentUser(): Promise<{
	id: string,
	name: string,
	/**
	 *  Public handle backing `/<username>`; mirrored from the auth response and stored locally so the
	 *  recipe `creator` resolves on-device.
	 */
	username: string,
	email: string,
	/**
	 *  Whether the account's email is verified. Serialized as `emailVerified` (keychain + TS bindings);
	 *  `post_auth` maps the backend's snake_case `email_verified` into it. Drives the verify banner.
	 */
	emailVerified: boolean,
} | null> {
    return invoke("current_user");
  },

  /** @throws {DataError} */
  signIn(input: SignInInput): Promise<AuthUser> {
    return invoke("sign_in", { input });
  },

  /** @throws {DataError} */
  signUp(input: SignUpInput): Promise<AuthUser> {
    return invoke("sign_up", { input });
  },

  /** @throws {DataError} */
  signOut(): Promise<null> {
    return invoke("sign_out");
  },

  /** @throws {DataError} */
  requestPasswordReset(input: ResetRequestInput): Promise<null> {
    return invoke("request_password_reset", { input });
  },

  /** @throws {DataError} */
  requestEmailVerification(input: ResetRequestInput): Promise<null> {
    return invoke("request_email_verification", { input });
  },
};

export type DataError = { type: "db"; message: string } | { type: "auth"; message: string };

export type AggregatedNutrition = {
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type Amount = {
	amount: number | null,
	unit: string | null,
	grams: number | null,
};

/**
 *  The current user, mirrored from the web auth response. Stamped on local writes, and upserted
 *  into the local `users` table so the foreign key (and the recipe `creator`) resolves on-device.
 */
export type AuthUser = {
	id: string,
	name: string,
	/**
	 *  Public handle backing `/<username>`; mirrored from the auth response and stored locally so the
	 *  recipe `creator` resolves on-device.
	 */
	username: string,
	email: string,
	/**
	 *  Whether the account's email is verified. Serialized as `emailVerified` (keychain + TS bindings);
	 *  `post_auth` maps the backend's snake_case `email_verified` into it. Drives the verify banner.
	 */
	emailVerified: boolean,
};

/**  Ingredient browser card (leaf ingredients — those not backing a recipe). */
export type IngredientCard = {
	id: string,
	name: string,
	caloriesPer100g: number | null,
	/**  Slug for the canonical `/ingredients/<slug>` link; fall back to `/ingredients/<id>`. */
	slug: string | null,
};

/**  IngredientForm edit-mode source data (per-100g; the frontend scales to per-serving). */
export type IngredientEditData = {
	id: string,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	nutrients: Reading[],
};

export type IngredientNutrientInput = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type IngredientSearchResult = {
	id: string,
	name: string,
	servingGrams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type IngredientSlugHit = {
	ingredientId: string,
	canonicalSlug: string,
};

/**
 *  One page of a catalog list: the sort, a keyset cursor (the last card's id, plus its name for the
 *  name sorts), and a page size. `Default` = newest-first, no cursor, no limit (the whole list).
 */
export type Page = {
	sort?: Sort,
	cursor?: string | null,
	cursorName?: string | null,
	limit?: number | null,
};

/**
 *  A public profile: the handle, the display name, and the user's visible recipes. Shared by the
 *  server's `/api/content/profile` endpoint and the desktop DAL so both render the identical screen.
 */
export type Profile = {
	username: string,
	name: string,
	recipes: RecipeCard[],
};

export type Reading = {
	name: string,
	amountPer100g: number | null,
	unit: string,
};

export type RecipeCard = {
	id: string,
	name: string,
	subtitle: string | null,
	/**
	 *  Owner handle + slug for the canonical `/<username>/<slug>` link. Optional (pre-backfill /
	 *  ownerless rows); the UI falls back to `/recipes/<id>` when either is missing.
	 */
	username: string | null,
	slug: string | null,
};

export type RecipeEditData = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servings: number | null,
	visibility: Visibility,
	items: RecipeEditItem[],
};

/**  RecipeForm edit-mode defaults: per-item nutrition included so each row shows live nutrition. */
export type RecipeEditItem = {
	ingredientId: string,
	name: string,
	grams: number | null,
	caloriesPer100g: number | null,
	readings: Reading[],
};

export type RecipeItem = {
	id: string,
	name: string,
	amount: Amount,
	/**
	 *  Set when this item is itself a recipe-as-ingredient (e.g. a Biga in a Dough),
	 *  so the UI links to that recipe's page instead of a (sparse) ingredient page.
	 */
	recipeId: string | null,
};

export type RecipeItemInput = {
	ingredientId: string,
	grams: number | null,
	unit: string | null,
};

export type RecipeSlugHit = {
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
};

export type RecipeView = {
	id: string,
	name: string,
	subtitle: string | null,
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	serving: Amount | null,
	batchGrams: number | null,
	items: RecipeItem[],
	nutrition: AggregatedNutrition,
};

export type ResetRequestInput = {
	email: string,
};

export type SaveIngredientInput = {
	id: string | null,
	visibility: Visibility | null,
	name: string,
	description: string | null,
	price: number | null,
	caloriesPer100g: number | null,
	servingGrams: number | null,
	packageGrams: number | null,
	nutrients: IngredientNutrientInput[],
	/**
	 *  SEO slug. `None` on a user create/edit ⇒ the DAL generates a unique one (and logs a rename to
	 *  slug_history). `Some` only on the sync pull-apply, which carries the SERVER's authoritative slug
	 *  so replicas never diverge. Serde-default so pre-slug payloads deserialize as None.
	 */
	slug?: string | null,
};

export type SaveRecipeInput = {
	id: string | null,
	/**
	 *  The recipe's as-ingredient id. Threaded so a nested recipe (a Biga consumed by a Dough as an
	 *  item) keeps a stable id cross-replica — else the consuming item's FK orphans after a pull.
	 *  `None` on a fresh local create (minted); set by the sync pull when mirroring server rows.
	 */
	asIngredientId: string | null,
	visibility: Visibility | null,
	name: string,
	subtitle: string | null,
	directions: string | null,
	servingGrams: number | null,
	batchGrams: number | null,
	items: RecipeItemInput[],
	/**
	 *  See SaveIngredientInput::slug. `None` ⇒ generate (unique per owner); `Some` ⇒ pull carries the
	 *  server's slug verbatim.
	 */
	slug?: string | null,
};

export type SignInInput = {
	email: string,
	password: string,
};

export type SignUpInput = {
	name: string,
	email: string,
	password: string,
};

/**
 *  Recipe browser cards. isListed: public catalog + your own (any visibility). `user_id = NULL` never
 *  matches, so a signed-out viewer (viewer = None) sees only public.
 *  Public recipe catalog for `viewer` (public rows + the viewer's own), NEWEST FIRST by id — ids are
 *  ULIDs, so id order is creation order. Keyset-paginated for infinite scroll: pass the last card's `id`
 *  as `cursor` to get the page after it; `limit` caps the page (None = no limit, i.e. the full list).
 *  Sort order for the catalog list reads. Recency sorts key on the id (ids are ULIDs, so id order is
 *  creation order); name sorts use a composite (name, id) keyset since names are not unique. Default
 *  = Newest (the catalog's first impression).
 */
export type Sort = "newest" | "oldest" | "name_asc" | "name_desc";

/**
 *  The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
 *  direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
 *  ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
 *  EDITING, not reading.
 */
export type Visibility = "public" | "private" | "unlisted";
