// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";

export const vegifyData = {
  /** @throws {DataError} */
  listRecipes(page: Page): Promise<RecipeCard[]> {
    return invoke("list_recipes", { page });
  },

  /** @throws {DataError} */
  recipe(id: string): Promise<{
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle under the title. */
	subtitle: string | null,
	/**  Free-text directions (markdown-ish plain text); None = none written. */
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	/**  Serving size, when declared (drives per-serving nutrition). */
	serving: Amount | null,
	/**
	 *  Total batch mass in grams, when declared — the denominator that
	 *  turns summed item nutrition into per-100 g.
	 */
	batchGrams: number | null,
	/**  The recipe's lines, in order. */
	items: RecipeItem[],
	/**  Nutrition rolled up from the items, per 100 g. */
	nutrition: AggregatedNutrition,
	/**  Media key of the hero photo — see [`RecipeCard::photo_key`]. */
	photoKey: string | null,
} | null> {
    return invoke("recipe", { id });
  },

  /** @throws {DataError} */
  getProfile(username: string): Promise<{
	/**  The profile's handle (URL segment). */
	username: string,
	/**  Display name. */
	name: string,
	/**  The user's recipes visible to the viewer, as cards. */
	recipes: RecipeCard[],
	/**
	 *  The user's LEAF ingredients (created or imported by them), visible to the viewer and not
	 *  tombstoned — browsable under `/<username>/ingredients/<slug>`.
	 */
	ingredients: IngredientCard[],
	/**  Media key of the profile avatar; clients compose `<api base>/<key>`. */
	avatarKey: string | null,
} | null> {
    return invoke("get_profile", { username });
  },

  /** @throws {DataError} */
  resolveRecipeBySlug(username: string, slug: string): Promise<{
	/**  The recipe the slug resolves to. */
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
} | null> {
    return invoke("resolve_recipe_by_slug", { username, slug });
  },

  /** @throws {DataError} */
  resolveIngredientBySlug(slug: string): Promise<{
	/**  The ingredient the slug resolves to. */
	ingredientId: string,
	/**
	 *  The ingredient's CURRENT slug — differs when the hit came from slug
	 *  history, in which case the caller 301s here.
	 */
	canonicalSlug: string,
	/**
	 *  Owner handle when the ingredient is user-owned: `/ingredients/<slug>` 301s to
	 *  `/<username>/ingredients/<slug>` (the catalog stays at the global path).
	 */
	username: string | null,
} | null> {
    return invoke("resolve_ingredient_by_slug", { slug });
  },

  /** @throws {DataError} */
  recipeForEdit(id: string): Promise<{
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle. */
	subtitle: string | null,
	/**  Free-text directions; None = none written. */
	directions: string | null,
	/**  Declared servings per batch, when set. */
	servings: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  The recipe's lines in edit form. */
	items: RecipeEditItem[],
} | null> {
    return invoke("recipe_for_edit", { id });
  },

  /** @throws {DataError} */
  listIngredients(page: Page): Promise<IngredientCard[]> {
    return invoke("list_ingredients", { page });
  },

  /** @throws {DataError} */
  ingredient(id: string): Promise<{
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Optional description shown on the detail page. */
	description: string | null,
	/**  Price in cents, when tracked. */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**
	 *  The serving's unit name (a count unit like "bun"/"slice"; "serving" by default). None ⇒ no
	 *  serving declared. Round-trips through the ingredient form so it can be renamed.
	 */
	servingUnit: string | null,
	/**  Package mass in grams, when declared (price-per-100 g math). */
	packageGrams: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	/**  Owner handle (None = the communal catalog) — the detail page's breadcrumb + canonical URL. */
	creator: string | null,
	/**  Per-100 g nutrient rows as stored (the form scales to per-serving). */
	nutrients: Reading[],
} | null> {
    return invoke("ingredient", { id });
  },

  /** @throws {DataError} */
  ingredientForEdit(id: string): Promise<{
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Optional description shown on the detail page. */
	description: string | null,
	/**  Price in cents, when tracked. */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**
	 *  The serving's unit name (a count unit like "bun"/"slice"; "serving" by default). None ⇒ no
	 *  serving declared. Round-trips through the ingredient form so it can be renamed.
	 */
	servingUnit: string | null,
	/**  Package mass in grams, when declared (price-per-100 g math). */
	packageGrams: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	/**  Owner handle (None = the communal catalog) — the detail page's breadcrumb + canonical URL. */
	creator: string | null,
	/**  Per-100 g nutrient rows as stored (the form scales to per-serving). */
	nutrients: Reading[],
} | null> {
    return invoke("ingredient_for_edit", { id });
  },

  /** @throws {DataError} */
  searchIngredients(query: string): Promise<IngredientSearchResult[]> {
    return invoke("search_ingredients", { query });
  },

  /** @throws {DataError} */
  saveIngredient(input: SaveIngredientInput): Promise<string> {
    return invoke("save_ingredient", { input });
  },

  /** @throws {DataError} */
  deleteIngredient(id: string): Promise<null> {
    return invoke("delete_ingredient", { id });
  },

  /** @throws {DataError} */
  restoreIngredient(id: string): Promise<null> {
    return invoke("restore_ingredient", { id });
  },

  /** @throws {DataError} */
  saveRecipe(input: SaveRecipeInput): Promise<string> {
    return invoke("save_recipe", { input });
  },

  /** @throws {DataError} */
  deleteRecipe(id: string): Promise<null> {
    return invoke("delete_recipe", { id });
  },

  /** @throws {DataError} */
  logDay(date: string): Promise<DayLog> {
    return invoke("log_day", { date });
  },

  /** @throws {DataError} */
  logRecents(limit: number | null): Promise<RecentIngredient[]> {
    return invoke("log_recents", { limit });
  },

  /** @throws {DataError} */
  saveLogEntry(input: SaveLogEntryInput): Promise<string> {
    return invoke("save_log_entry", { input });
  },

  /** @throws {DataError} */
  deleteLogEntry(id: string): Promise<null> {
    return invoke("delete_log_entry", { id });
  },

  /** @throws {DataError} */
  getNutritionProfile(): Promise<NutritionProfile> {
    return invoke("get_nutrition_profile");
  },

  /** @throws {DataError} */
  saveNutritionProfile(input: NutritionProfile): Promise<null> {
    return invoke("save_nutrition_profile", { input });
  },

  /** @throws {DataError} */
  saveDaySupplements(input: DaySupplementsRecord): Promise<null> {
    return invoke("save_day_supplements", { input });
  },

  /** @throws {DataError} */
  syncNow(): Promise<null> {
    return invoke("sync_now");
  },

  /** @throws {DataError} */
  currentUser(): Promise<{
	/**  User id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Public handle backing `/<username>`. */
	username: string,
	/**  Login/notification address (the account's own view). */
	email: string,
	/**
	 *  Whether the account's email is verified (serialized `emailVerified`; the auth response's
	 *  snake_case `email_verified` is mapped in [`VegifyClient::sign_in`]/[`sign_up`]).
	 */
	emailVerified: boolean,
} | null> {
    return invoke("current_user");
  },

  /** @throws {DataError} */
  mediaBase(): Promise<string> {
    return invoke("media_base");
  },

  /** @throws {DataError} */
  signIn(input: SignInInput): Promise<AuthUser> {
    return invoke("sign_in", { input });
  },

  /** @throws {DataError} */
  signUp(input: SignUpInput): Promise<AuthUser> {
    return invoke("sign_up", { input });
  },

  /** @throws {DataError} */
  signOut(): Promise<null> {
    return invoke("sign_out");
  },

  /** @throws {DataError} */
  requestPasswordReset(input: ResetRequestInput): Promise<null> {
    return invoke("request_password_reset", { input });
  },

  /** @throws {DataError} */
  requestEmailVerification(input: ResetRequestInput): Promise<null> {
    return invoke("request_email_verification", { input });
  },

  /** @throws {DataError} */
  messageConversations(): Promise<ConversationSummary[]> {
    return invoke("message_conversations");
  },

  /** @throws {DataError} */
  messageThread(username: string): Promise<Thread> {
    return invoke("message_thread", { username });
  },

  /** @throws {DataError} */
  sendMessage(input: SendMessageInput): Promise<Message> {
    return invoke("send_message", { input });
  },

  /** @throws {DataError} */
  messagesUnread(): Promise<number | null> {
    return invoke("messages_unread");
  },

  /** @throws {DataError} */
  notifications(): Promise<DmNotification[]> {
    return invoke("notifications");
  },

  /** @throws {DataError} */
  notificationsUnread(): Promise<number | null> {
    return invoke("notifications_unread");
  },

  /** @throws {DataError} */
  notificationsMarkRead(): Promise<null> {
    return invoke("notifications_mark_read");
  },

  /** @throws {DataError} */
  reportContent(targetType: string, targetId: string, reason: string, note: string): Promise<null> {
    return invoke("report_content", { target_type: targetType, target_id: targetId, reason, note });
  },

  /** @throws {DataError} */
  blockUser(username: string): Promise<null> {
    return invoke("block_user", { username });
  },

  /** @throws {DataError} */
  unblockUser(username: string): Promise<null> {
    return invoke("unblock_user", { username });
  },

  /** @throws {DataError} */
  deleteAccount(password: string): Promise<null> {
    return invoke("delete_account", { password });
  },
};

export type DataError = { type: "db"; message: string } | { type: "auth"; message: string };

/**  A recipe's nutrition rolled up from its items, per 100 g. */
export type AggregatedNutrition = {
	/**  Calories per 100 g; None when no item carries calorie data. */
	caloriesPer100g: number | null,
	/**  Per-100 g readings summed across items, keyed by nutrient name. */
	readings: Reading[],
};

/**
 *  A quantity as entered plus its canonical mass: `grams` is the ground
 *  truth all math runs on; `amount`/`unit` preserve how the user wrote it.
 */
export type Amount = {
	/**  Quantity in `unit`, as entered; None when only the mass is known. */
	amount: number | null,
	/**  Display unit (cup, tbsp, g); None when only the mass is known. */
	unit: string | null,
	/**  Canonical mass in grams. */
	grams: number | null,
};

/**  The signed-in user, as the auth routes return it. */
export type AuthUser = {
	/**  User id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Public handle backing `/<username>`. */
	username: string,
	/**  Login/notification address (the account's own view). */
	email: string,
	/**
	 *  Whether the account's email is verified (serialized `emailVerified`; the auth response's
	 *  snake_case `email_verified` is mapped in [`VegifyClient::sign_in`]/[`sign_up`]).
	 */
	emailVerified: boolean,
};

/**  One conversation row of the DM list, newest-message first. */
export type ConversationSummary = {
	/**  Conversation id. */
	id: string,
	/**  The other party. */
	with: Party,
	/**  Body of the newest message (the list's preview line). */
	lastBody: string,
	/**  Newest message timestamp, ms epoch. */
	lastAt: number,
	/**  True when the last message is the viewer's own (the list renders "You: …"). */
	lastIsMine: boolean,
	/**  Count of messages the viewer has not read (SQLite COUNT() is i64). */
	unread: number,
};

/**
 *  One diary day: the entries plus server-computed nutrient totals, each rolled up from its entry via
 *  the SAME recursive CTE recipes use (so a logged recipe expands through its nesting). PRIVATE — only
 *  ever returned to its owner, never listed, never in the anonymous pull.
 */
export type DayLog = {
	/**  The 'YYYY-MM-DD' this day covers (echoes the request). */
	date: string,
	/**  The day's live entries, newest logged first. */
	entries: LogEntryView[],
	/**  Total calories for the day; None when no entry carries calorie data. */
	calories: number | null,
	/**  Per-nutrient absolute totals for the day, ordered by nutrient name. */
	totals: NutrientTotal[],
	/**
	 *  The viewer's personalized vegan-aware daily targets (from their profile; generic-adult when
	 *  unset), with per-DAY supplement coverage applied. Returned per-day so the Day screen can render
	 *  progress vs. targets in one payload. Match a `total` to its `target` by nutrient name.
	 */
	targets: NutrientTarget[],
	/**
	 *  The supplements taken on this day (effective, carry-forward). Renders the day's supplement
	 *  checklist and drives the `supplementCovered` flags above.
	 */
	supplements: DaySupplements,
};

/**
 *  The supplements taken on a given DAY — the vegan-critical ones whose targets read as "covered by a
 *  supplement" rather than a food gap. This is per-DAY state (part of the day's plan), NOT a standing
 *  profile setting: whether you took your B12 today is a fact about today, and coverage should reflect
 *  it honestly. Carry-forward (`get_day_supplements`) makes a new day inherit your last day's routine so
 *  you don't re-check the same boxes every morning. Every field defaults to false (nothing taken).
 */
export type DaySupplements = {
	/**  Took a B12 supplement (or reliably ate fortified foods) ⇒ the B12 target shows as covered. */
	b12?: boolean,
	/**  Took a vitamin D supplement ⇒ the vitamin D target shows as covered. */
	vitD?: boolean,
	/**  Took an algae-oil (EPA+DHA) supplement ⇒ the omega-3 note reflects it. */
	algaeOil?: boolean,
};

/**
 *  A dated supplement record: the supplements taken on one `date`. Doubles as the authed-pull row (to
 *  rebuild the day_supplements table on a replica verbatim) and the `save_day_supplements` write payload.
 */
export type DaySupplementsRecord = {
	/**  User-local calendar date 'YYYY-MM-DD' this record pins (incl. the '1970-01-01' migration floor). */
	date: string,
	/**  Took a B12 supplement that day. */
	b12: boolean,
	/**  Took a vitamin D supplement that day. */
	vitD: boolean,
	/**  Took an algae-oil (EPA+DHA) supplement that day. */
	algaeOil: boolean,
};

/**
 *  One bell row, as CONSUMERS see it: `payload` is the server's per-kind JSON re-serialized to a
 *  RAW STRING (consumers parse it by `kind`). The wire shape itself is [`Notification`]
 *  (`payload` as parsed JSON); this view exists so IPC/webview consumers get a string they can
 *  hand straight to `JSON.parse`.
 */
export type DmNotification = {
	/**  Notification id. */
	id: string,
	/**  Kind tag (e.g. "ingredient-updated"); selects the payload shape. */
	kind: string,
	/**  Raw per-kind JSON payload; the desktop parses it by `kind`. */
	payload: string,
	/**  Creation timestamp, ms epoch (f64 on this wire). */
	createdAt: number | null,
	/**  Whether the viewer has opened it. */
	read: boolean,
};

/**
 *  Which DRI reference column to read. Male and female adult nutrient requirements genuinely differ
 *  (iron, zinc, calcium, …), so a target must know which table applies. This is a NUTRITION parameter,
 *  NOT a statement of gender identity: it is optional, falls back to a protective generic tier when
 *  unset, and any individual target stays overridable.
 */
export type DriSex = 
/**  Read the male DRI column. */
"male" | 
/**  Read the female DRI column. */
"female";

/**  Ingredient browser card (leaf ingredients — those not backing a recipe). */
export type IngredientCard = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Calories per 100 g, when known (list-card badge). */
	caloriesPer100g: number | null,
	/**  Slug for the canonical link; fall back to `/ingredients/<id>`. */
	slug: string | null,
	/**
	 *  Owner handle: an OWNED ingredient is canonical at `/<username>/ingredients/<slug>` (browsable
	 *  under its creator); None = the communal catalog, canonical at `/ingredients/<slug>`.
	 */
	username: string | null,
};

/**  IngredientForm edit-mode source data (per-100g; the frontend scales to per-serving). */
export type IngredientEditData = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**  Optional description shown on the detail page. */
	description: string | null,
	/**  Price in cents, when tracked. */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**
	 *  The serving's unit name (a count unit like "bun"/"slice"; "serving" by default). None ⇒ no
	 *  serving declared. Round-trips through the ingredient form so it can be renamed.
	 */
	servingUnit: string | null,
	/**  Package mass in grams, when declared (price-per-100 g math). */
	packageGrams: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  Canonical URL segment `/ingredients/<slug>`. None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this ingredient — drives the edit affordance in the UI. Always
	 *  true on the owner-only edit-load path; on the detail path it reflects ownership (false for
	 *  anonymous + non-owner viewers). The real guard stays server-side.
	 */
	canEdit: boolean,
	/**
	 *  Soft-deleted (tombstoned) by its owner: delisted from browse/search but preserved for the
	 *  recipes that use it. Detail renders a badge; lists never surface it.
	 */
	deleted: boolean,
	/**  Owner handle (None = the communal catalog) — the detail page's breadcrumb + canonical URL. */
	creator: string | null,
	/**  Per-100 g nutrient rows as stored (the form scales to per-serving). */
	nutrients: Reading[],
};

/**  One nutrient row of a SaveIngredientInput, normalized per 100 g. */
export type IngredientNutrientInput = {
	/**  Nutrient name (e.g. "Iron"). */
	name: string,
	/**  Quantity per 100 g. */
	amountPer100g: number | null,
	/**  Unit for the quantity (g, mg, µg). */
	unit: string,
};

/**  One ingredient hit in the recipe composer's search box. */
export type IngredientSearchResult = {
	/**  Ingredient id. */
	id: string,
	/**  Ingredient name. */
	name: string,
	/**
	 *  Serving size in grams, when the ingredient declares one (the composer's
	 *  default line quantity).
	 */
	servingGrams: number | null,
	/**
	 *  The serving's unit name (a count unit like "bun"/"slice"; "serving" by default) — the composer
	 *  offers it as a count unit whose grams factor is `serving_grams`. None ⇒ no serving declared.
	 */
	servingUnit: string | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Per-100 g nutrient readings, for the composer's live nutrition preview. */
	readings: Reading[],
};

/**  Resolution of an ingredient slug (current or historical) to its row. */
export type IngredientSlugHit = {
	/**  The ingredient the slug resolves to. */
	ingredientId: string,
	/**
	 *  The ingredient's CURRENT slug — differs when the hit came from slug
	 *  history, in which case the caller 301s here.
	 */
	canonicalSlug: string,
	/**
	 *  Owner handle when the ingredient is user-owned: `/ingredients/<slug>` 301s to
	 *  `/<username>/ingredients/<slug>` (the catalog stays at the global path).
	 */
	username: string | null,
};

/**
 *  One diary entry as read: what was logged, how much, and — when the logged row is itself a
 *  recipe-as-ingredient — a link to that recipe (mirrors RecipeItem.recipe_id). `calories` is this
 *  entry's own contribution (its per-100g rollup × grams/100), for the row display.
 */
export type LogEntryView = {
	/**  The entry id. */
	id: string,
	/**  User-local calendar date 'YYYY-MM-DD'. */
	date: string,
	/**  Meal slot; currently unused by the UI. */
	slot: string | null,
	/**  The logged ingredient's id (a recipe's as-ingredient id when a recipe was logged). */
	ingredientId: string,
	/**  Ingredient (or recipe) display name at read time. */
	name: string,
	/**  Set when the logged row is itself a recipe-as-ingredient, so the UI links to the recipe page. */
	recipeId: string | null,
	/**  The amount logged (display form + canonical grams). */
	amount: Amount,
	/**  This entry's calorie contribution (per-100g rollup × grams/100), when calorie data exists. */
	calories: number | null,
	/**  When it was logged (ms epoch). */
	loggedAt: number,
};

/**  One DM as the thread screen renders it. */
export type Message = {
	/**  Message id. */
	id: string,
	/**  Message body (plain text). */
	body: string,
	/**  Send timestamp, ms epoch. */
	createdAt: number,
	/**  True when the viewer sent it (clients render alignment off this, not off raw ids). */
	mine: boolean,
};

/**
 *  One personalized daily target for a nutrient. `name`/`unit` match the ingredient catalog's naming
 *  (crates/usda-importer NUTRIENTS) so a day `NutrientTotal` compares to it directly.
 */
export type NutrientTarget = {
	/**  Canonical nutrient name, matching `NutrientTotal.name` (e.g. "Iron", "Vitamin B12"). */
	name: string,
	/**  The personalized daily goal, in `unit`. */
	amount: number | null,
	/**  Unit — the catalog's storage unit for this nutrient ("mg" | "µg" | "g" | "IU"). */
	unit: string,
	/**  RDA vs AI, for honest labelling. */
	basis: TargetBasis,
	/**  True when the vegan bioavailability overlay raised this above the plain DRI (iron, zinc, protein). */
	veganAdjusted: boolean,
	/**
	 *  True when a logged supplement flag covers this nutrient (B12 / vitamin D) — display it as met by
	 *  supplement rather than as a food gap.
	 */
	supplementCovered: boolean,
	/**  Short guidance note (vegan-specific context). Guidance-toned, never shaming. None = no note. */
	note: string | null,
};

/**
 *  One nutrient's ABSOLUTE total for a day (summed across entries), keyed by name + unit. Distinct
 *  from `Reading`, which is per-100g.
 */
export type NutrientTotal = {
	/**  Nutrient name (e.g. "Iron"). */
	name: string,
	/**  Absolute amount for the day, in `unit`. */
	amount: number | null,
	/**  Display unit (g, mg, µg). */
	unit: string,
};

/**
 *  The per-user nutrition profile. Every field is OPTIONAL — an empty profile (or an absent field)
 *  yields the generic-adult target tier, so targets ALWAYS exist. PRIVATE: only ever read/written by
 *  its owner, never listed or in the anonymous pull. Doubles as the write payload (`save_profile`) and
 *  the read shape (`get_profile`); `#[serde(default)]` lets a partial `{}` deserialize.
 */
export type NutritionProfile = {
	/**  Birth year → coarse DRI age bracket (19–50 / 51–70 / 71+). None ⇒ the 19–50 adult tier. */
	birthYear?: number | null,
	/**  Which DRI column to read. None ⇒ the protective generic tier (max of the sexes, per nutrient). */
	driSex?: DriSex | null,
	/**  Body weight (kg) for the protein g/kg target. None ⇒ the reference-weight gram RDA. */
	weightKg?: number | null,
	/**  Pregnancy raises the iron / iodine / zinc / B12 / selenium DRIs; overrides the sex column. */
	pregnancy?: boolean,
	/**  Lactation DRIs (distinct from pregnancy); overrides the sex column. */
	lactation?: boolean,
};

/**
 *  One page of a catalog list: the sort, a keyset cursor (the last card's id, plus its name for the
 *  name sorts), and a page size. `Default` = newest-first, no cursor, no limit (the whole list).
 */
export type Page = {
	/**  Sort order for the page. */
	sort?: Sort,
	/**  Keyset cursor: the last card's id from the previous page. */
	cursor?: string | null,
	/**  The last card's name, required by the name sorts' keyset. */
	cursorName?: string | null,
	/**  Page size; None = unbounded. */
	limit?: number | null,
};

/**  The other party, as the conversation list + thread header shows them. */
export type Party = {
	/**  User id. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Public handle (`/<username>`). */
	username: string,
};

/**
 *  A public profile: the handle, the display name, and the user's visible recipes. Shared by the
 *  server's `/api/content/profile` endpoint and the desktop DAL so both render the identical screen.
 */
export type Profile = {
	/**  The profile's handle (URL segment). */
	username: string,
	/**  Display name. */
	name: string,
	/**  The user's recipes visible to the viewer, as cards. */
	recipes: RecipeCard[],
	/**
	 *  The user's LEAF ingredients (created or imported by them), visible to the viewer and not
	 *  tombstoned — browsable under `/<username>/ingredients/<slug>`.
	 */
	ingredients: IngredientCard[],
	/**  Media key of the profile avatar; clients compose `<api base>/<key>`. */
	avatarKey: string | null,
};

/**  One nutrient measurement, normalized per 100 g. */
export type Reading = {
	/**  Nutrient name (e.g. "Iron"). */
	name: string,
	/**  Quantity per 100 g of the food. */
	amountPer100g: number | null,
	/**  Display unit for the quantity (g, mg, µg). */
	unit: string,
};

/**
 *  A recently/frequently logged ingredient, surfaced so re-logging is fast (the add-flow prepends
 *  these before global search — personal ranking beats global relevance for logging speed).
 */
export type RecentIngredient = {
	/**  The ingredient's id (a recipe's as-ingredient id when a recipe). */
	ingredientId: string,
	/**  Display name. */
	name: string,
	/**  Set when it's a recipe-as-ingredient (the UI can badge/link it). */
	recipeId: string | null,
	/**  How many times the user has logged it (lifetime, non-deleted). */
	count: number,
	/**  The most recent log's grams, to prefill the amount on re-log. */
	lastGrams: number | null,
	/**  The most recent log's display unit, if any. */
	lastUnit: string | null,
	/**  When it was last logged (ms epoch). */
	lastLoggedAt: number,
};

/**  Recipe list/browse card — the light projection for grids. */
export type RecipeCard = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle, shown under the title on cards. */
	subtitle: string | null,
	/**
	 *  Owner handle + slug for the canonical `/<username>/<slug>` link. Optional (pre-backfill /
	 *  ownerless rows); the UI falls back to `/recipes/<id>` when either is missing.
	 */
	username: string | null,
	/**  The recipe's slug half of the canonical link (see `username`). */
	slug: string | null,
	/**
	 *  Media key of the hero photo (attached to the recipe's as-ingredient); clients compose the
	 *  URL as `<api base>/<key>`. None = no photo yet (cards render the placeholder tile).
	 */
	photoKey: string | null,
};

/**  RecipeForm edit-mode source data (per-100 g; the frontend scales). */
export type RecipeEditData = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle. */
	subtitle: string | null,
	/**  Free-text directions; None = none written. */
	directions: string | null,
	/**  Declared servings per batch, when set. */
	servings: number | null,
	/**  Current visibility. */
	visibility: Visibility,
	/**  The recipe's lines in edit form. */
	items: RecipeEditItem[],
};

/**  RecipeForm edit-mode defaults: per-item nutrition included so each row shows live nutrition. */
export type RecipeEditItem = {
	/**  The referenced ingredient's id. */
	ingredientId: string,
	/**  Ingredient display name. */
	name: string,
	/**  Line quantity in grams (canonical). */
	grams: number | null,
	/**  The count in `unit` the author entered (e.g. 2 for "2 buns"); mirrors grams on a legacy line. */
	amount: number | null,
	/**  Display unit for `amount`; None ⇒ grams. */
	unit: string | null,
	/**  "units" (show `amount unit`) or "grams" (show grams) — how the line was entered. */
	preferred: string,
	/**  Calories per 100 g, when known — the edit screen's live math. */
	caloriesPer100g: number | null,
	/**  Per-100 g readings for the edit screen's live nutrition roll-up. */
	readings: Reading[],
};

/**  One recipe line as read: the ingredient, its display name, its amount. */
export type RecipeItem = {
	/**  The underlying ingredient's id. */
	id: string,
	/**  Ingredient display name at read time. */
	name: string,
	/**  The line's quantity (display form + canonical grams). */
	amount: Amount,
	/**
	 *  Set when this item is itself a recipe-as-ingredient (e.g. a Biga in a Dough),
	 *  so the UI links to that recipe's page instead of a (sparse) ingredient page.
	 */
	recipeId: string | null,
	/**
	 *  True only in the DELETER's own recipes: the ingredient is soft-deleted (tombstoned) AND its
	 *  owner owns this recipe. Other users' recipes render the same ingredient normally — a soft
	 *  delete disowns from the catalog without breaking anyone's recipe. Drives the greyed row +
	 *  the "restore?" affordance.
	 */
	deleted: boolean,
};

/**
 *  One line of a SaveRecipeInput: which ingredient, how much. `grams` is always canonical (all
 *  nutrition math reads it); `amount` + `unit` are the display form the user entered (e.g. 2 "bun"),
 *  preserved so the line reads naturally instead of as raw grams.
 */
export type RecipeItemInput = {
	/**  The ingredient this line references. */
	ingredientId: string,
	/**  Line quantity in grams (canonical). */
	grams: number | null,
	/**  Display unit the user picked; None ⇒ grams. */
	unit: string | null,
	/**  The count in `unit` (e.g. 2 for "2 buns"). None ⇒ legacy grams-only line (amount == grams). */
	amount?: number | null,
};

/**  Resolution of a recipe slug (current or historical) to its row. */
export type RecipeSlugHit = {
	/**  The recipe the slug resolves to. */
	recipeId: string,
	/**
	 *  The recipe's CURRENT slug. When it differs from the requested slug, the caller 301s to
	 *  `/<username>/<canonical_slug>`.
	 */
	canonicalSlug: string,
};

/**  Full recipe detail as rendered by the recipe page. */
export type RecipeView = {
	/**  Recipe id. */
	id: string,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle under the title. */
	subtitle: string | null,
	/**  Free-text directions (markdown-ish plain text); None = none written. */
	directions: string | null,
	/**  The owner's username — also the first segment of the canonical URL `/<creator>/<slug>`. */
	creator: string | null,
	/**  This recipe's current slug (the `/<creator>/<slug>` segment). None only pre-backfill. */
	slug: string | null,
	/**
	 *  Whether the current viewer owns this recipe — drives the edit affordance in the UI. The real
	 *  guard stays server-side (owner-only edit-load + mutation); false for anonymous + non-owner viewers.
	 */
	canEdit: boolean,
	/**  Serving size, when declared (drives per-serving nutrition). */
	serving: Amount | null,
	/**
	 *  Total batch mass in grams, when declared — the denominator that
	 *  turns summed item nutrition into per-100 g.
	 */
	batchGrams: number | null,
	/**  The recipe's lines, in order. */
	items: RecipeItem[],
	/**  Nutrition rolled up from the items, per 100 g. */
	nutrition: AggregatedNutrition,
	/**  Media key of the hero photo — see [`RecipeCard::photo_key`]. */
	photoKey: string | null,
};

/**  Password-reset request payload. */
export type ResetRequestInput = {
	/**  The account email to send the reset link to. */
	email: string,
};

/**
 *  Create-or-update payload for an ingredient. `id: Some` updates that row
 *  (owner-guarded); `None` creates, minting the id.
 */
export type SaveIngredientInput = {
	/**
	 *  Existing row to update, or None to create. Client-supplied ids are
	 *  honored so sync replays are idempotent cross-replica.
	 */
	id: string | null,
	/**  Visibility to set; None keeps the default (public). */
	visibility: Visibility | null,
	/**  Ingredient name. */
	name: string,
	/**  Optional description. */
	description: string | null,
	/**  Price in cents, when tracked. */
	price: number | null,
	/**  Calories per 100 g, when known. */
	caloriesPer100g: number | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**
	 *  The serving's unit name (a count unit like "bun"/"slice"; None ⇒ "serving"). Stored on the
	 *  serving amount's `unit`, so a recipe line can be entered as a count of it.
	 */
	servingUnit?: string | null,
	/**  Package mass in grams, when declared. */
	packageGrams: number | null,
	/**  Per-100 g nutrient rows (replaces the stored set). */
	nutrients: IngredientNutrientInput[],
	/**
	 *  SEO slug. `None` on a user create/edit ⇒ the DAL generates a unique one (and logs a rename to
	 *  slug_history). `Some` only on the sync pull-apply, which carries the SERVER's authoritative slug
	 *  so replicas never diverge. Serde-default so pre-slug payloads deserialize as None.
	 */
	slug?: string | null,
};

/**
 *  Create-or-update payload for a diary entry. `id: Some` + an existing row updates it (owner-gated);
 *  `id: Some` + no such row inserts WITH that id (an offline create's client ULID / a sync replay);
 *  `id: None` mints a fresh ULID. Logging a recipe = passing its as-ingredient id as `ingredientId`.
 */
export type SaveLogEntryInput = {
	/**
	 *  Existing entry to update, or None to create (id minted). Client ids are honored so replays
	 *  stay idempotent cross-replica.
	 */
	id: string | null,
	/**  The ingredient — or a recipe's as_ingredient_id — being logged. */
	ingredientId: string,
	/**  User-local calendar date 'YYYY-MM-DD', chosen client-side (no server timezone modeling). */
	date: string,
	/**
	 *  Meal slot (breakfast/lunch/dinner/snack); currently ignored by the UI. Serde-default so
	 *  slot-less payloads deserialize.
	 */
	slot?: string | null,
	/**  Amount logged, canonical grams. */
	grams: number | null,
	/**  Display unit the user picked; None = grams. Mirrors RecipeItemInput. */
	unit?: string | null,
	/**  When it was logged (ms epoch); None ⇒ now. Set by a sync replay to preserve ordering. */
	loggedAt?: number | null,
};

/**
 *  Create-or-update payload for a recipe; ids are honored when supplied so
 *  sync replays are idempotent cross-replica.
 */
export type SaveRecipeInput = {
	/**  Existing recipe to update, or None to create (id minted). */
	id: string | null,
	/**
	 *  The recipe's as-ingredient id. Threaded so a nested recipe (a Biga consumed by a Dough as an
	 *  item) keeps a stable id cross-replica — else the consuming item's FK orphans after a pull.
	 *  `None` on a fresh local create (minted); set by the sync pull when mirroring server rows.
	 */
	asIngredientId: string | null,
	/**  Visibility to set; None keeps the default (public). */
	visibility: Visibility | null,
	/**  Recipe title. */
	name: string,
	/**  Optional subtitle. */
	subtitle: string | null,
	/**  Free-text directions. */
	directions: string | null,
	/**  Serving size in grams, when declared. */
	servingGrams: number | null,
	/**  Total batch mass in grams, when declared. */
	batchGrams: number | null,
	/**  The recipe's lines (replaces the stored set, in order). */
	items: RecipeItemInput[],
	/**
	 *  See SaveIngredientInput::slug. `None` ⇒ generate (unique per owner); `Some` ⇒ pull carries the
	 *  server's slug verbatim.
	 */
	slug?: string | null,
};

/**  Send-DM payload. */
export type SendMessageInput = {
	/**  Recipient username. */
	to: string,
	/**  Message body (plain text). */
	body: string,
};

/**  Sign-in form payload. */
export type SignInInput = {
	/**  Login email. */
	email: string,
	/**  Plaintext password (sent to the server, never stored). */
	password: string,
};

/**  Sign-up form payload. */
export type SignUpInput = {
	/**  Display name. */
	name: string,
	/**  Login email. */
	email: string,
	/**  Plaintext password (sent to the server, never stored). */
	password: string,
};

/**
 *  Recipe browser cards. isListed: public catalog + your own (any visibility). `user_id = NULL` never
 *  matches, so a signed-out viewer (viewer = None) sees only public.
 *  Public recipe catalog for `viewer` (public rows + the viewer's own), NEWEST FIRST by id — ids are
 *  ULIDs, so id order is creation order. Keyset-paginated for infinite scroll: pass the last card's `id`
 *  as `cursor` to get the page after it; `limit` caps the page (None = no limit, i.e. the full list).
 *  Sort order for the catalog list reads. Recency sorts key on the id (ids are ULIDs, so id order is
 *  creation order); name sorts use a composite (name, id) keyset since names are not unique. Default
 *  = Newest (the catalog's first impression).
 */
export type Sort = 
/**  Newest first (creation order). */
"newest" | 
/**  Oldest first. */
"oldest" | 
/**  Name A→Z. */
"name_asc" | 
/**  Name Z→A. */
"name_desc";

/**
 *  Whether a target is an RDA (meets ~97–98% of the population's needs) or an AI (Adequate Intake,
 *  used where the evidence can't set an RDA — e.g. omega-3 ALA). Surfaced so the UI can be honest.
 */
export type TargetBasis = 
/**  Recommended Dietary Allowance — meets the needs of ~97–98% of healthy people. */
"rda" | 
/**  Adequate Intake — used where the evidence can't establish an RDA (e.g. omega-3 ALA). */
"ai";

/**
 *  A thread as the thread screen consumes it: the other party (resolved even before any message
 *  exists, so a profile's "Message" button lands on an empty composer) + the messages, oldest first.
 */
export type Thread = {
	/**  The other party (resolved even for an empty thread). */
	with: Party,
	/**  The messages, oldest first. */
	messages: Message[],
};

/**
 *  The app is public-default sharing: `public` = anyone lists+reads; `unlisted` = readable by
 *  direct id/link but not listed; `private` = owner only. Stored on `ingredients` — a recipe IS an
 *  ingredient (`as_ingredient_id`), so this one field covers both. Ownership (`user_id`) gates
 *  EDITING, not reading.
 */
export type Visibility = 
/**  Listed and readable by everyone. */
"public" | 
/**  Readable only by the owner. */
"private" | 
/**  Readable via direct link; never listed or searched. */
"unlisted";
